SET NAMES utf8;
SET SQL_MODE='';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0;

CREATE DATABASE IF NOT EXISTS `family` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE `family`;


/* Create table `person` */
DROP TABLE IF EXISTS `person`;

CREATE TABLE `person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) DEFAULT NULL, 
  `passport` VARCHAR(255) DEFAULT NULL, 
  `pascal` BOOL DEFAULT NULL, 
  `age` INT DEFAULT NULL, 
  `father_id` INT DEFAULT NULL, 
  UNIQUE KEY `uk_family_person_natural_key` (`passport`),
  CONSTRAINT `fk_family_person_father` FOREIGN KEY (`father_id`) REFERENCES `person` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION, 
  KEY `idx_family_person_father` (`father_id`), 
  PRIMARY KEY (`id`)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET SQL_NOTES=@OLD_SQL_NOTES;